Introduce a list command to list all transients
wp-cli/cache-command pull request #48
Opened 2018-11-19 22:09 UTC by ocean90

Fixes #44.

2018-11-20 17:05 UTC, ocean90 commented on src/Transient_Command.php
> +		return human_time_diff( $now, $expiration );
Make this machine readable by default

2018-11-20 17:05 UTC, ocean90 commented on src/Transient_Command.php
> +	 *
Let's also add arguments for filtering.

2018-11-20 17:06 UTC, schlessera requested changes

2018-11-20 17:06 UTC, schlessera commented on src/Transient_Command.php
> +	 * is a specially-named cache key. On multisite, this is a global cache
```suggestion
	 * a specially-named cache key. On multisite, this is a global cache
```

2018-11-20 17:06 UTC, schlessera commented on features/transient.feature
> +      foo,bar,"no expiration"
On the non-human output, should the expiration here return `false`?

2018-12-01 19:33 UTC, schlessera approved these changes

2018-12-01 19:34 UTC, merged

2018-12-01 19:34 UTC, schlessera commented
Thanks for the PR, @ocean90 !